# Generated by Django 5.0.6 on 2024-05-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='udated_at',
            new_name='updated_at',
        ),
    ]
